config/routes.rb
Rails.application.routes.draw do
  # root path is '/' or '/users'
  root 'users#index'
  devise_for :users
  delete '/users/sign_out', to: 'devise/sessions#destroy', as: 'logout'
  resources :users do
    resources :posts do
      resources :comments
      resources :likes
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.role == 'admin'
      can :manage, [Post, Comment, Like]
    else
      can :manage, [Post, Comment, Like], author_id: user.id
    end

    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, class_name: 'Post'

  after_save :update_comment_counter

  def update_comment_counter
    post.increment!(:comment_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, class_name: 'Post'

  after_save :update_like_counter

  def update_like_counter
    post.increment!(:like_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, class_name: 'Comment', foreign_key: 'post_id'
  has_many :likes, class_name: 'Like', foreign_key: 'post_id'

  validates :title, presence: { strict: true }, length: { minimum: 3, maximum: 250 }
  validates :comment_counter, :like_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_post_counter

  def update_post_counter
    author.increment!(:post_counter)
  end

  def five_recent_comments
    comments.includes(:author).order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :posts, class_name: 'Post', foreign_key: 'author_id'
  has_many :comments, class_name: 'Comment', foreign_key: 'author_id'
  has_many :likes, class_name: 'Like', foreign_key: 'author_id'

  validates :name, presence: { strict: true }
  validates :post_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def three_recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def after_sign_out_path_for(_resource_or_scope)
    request.referrer
    '/users/sign_in'
  end

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :photo, :bio, :email, :password, :password_confirmation, :confirmation_token)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :photo, :bio, :email, :password, :current_password, :confirmation_token)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @post = Post.find(params[:post_id])
    respond_to do |format|
      format.html
      format.json do
        if current_user.id == params[:user_id].to_i
          render json: @post.comments
        else
          render html: "You are not authorized to see someone else's data"
        end
      end
    end
  end

  def new
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @user = current_user
    new_comment = current_user.comments.new(comment_params)
    if new_comment.save
      redirect_to user_post_path(user_id: @user.id, id: @post.id), notice: 'Success Comment Saved!'
    else
      flash[:notice] = 'comment does not saved !'
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @user = @post.author

    return unless @comment.destroy

    @post.decrement!(:comment_counter)
    redirect_to user_post_path(user_id: @user.id, id: @post.id)
  end

  private

  def comment_params
    params.permit(:text, :author_id, :post_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @post = Post.find(params[:post_id])

    new_like = current_user.likes.new(author_id: current_user.id, post_id: @post.id)
    if new_like.save
      redirect_to user_post_path(user_id: current_user.id, id: @post.id), notice: 'Success Comment Saved!'
    else
      flash[:notice] = 'comment does not saved !'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = Post.where(author_id: @user.id)
  end

  def show
    @post = Post.includes(:author, comments: [:author]).find(params[:id])
    @user = @post.author
    respond_to do |format|
      format.html
      format.json do
        if current_user.id == params[:user_id].to_i
          render json: @post.comments
        else
          render html: "You are not authorized to see someone else's data"
        end
      end
    end
  end

  def new
    @user = User.find(params[:user_id])
    @post = Post.new
  end

  def create
    new_post = current_user.posts.new(params_data)
    if new_post.save
      redirect_to user_path(id: current_user.id)
    else
      redirect_to new_user_post_path
    end
  end

  def destroy
    @post = Post.includes(:comments, :likes).find(params[:id])
    @user = current_user
    @post.comments.each(&:destroy)
    @post.likes.each(&:destroy)
    return unless @post.destroy

    @post.author.decrement!(:post_counter)
    redirect_to user_path(id: @user.id)
  end

  private

  def params_data
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  protect_from_forgery
  before_action :authenticate_user!

  # Actions
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html
      format.json do
        if current_user.id == params[:id].to_i
          render json: @user.posts
        else
          render html: "You are not authorized to see someone else's data"
        end
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myclan</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class = 'notice'><%= notice %></p>
    <p class = 'alert'><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/partials/_comment.html.erb
<div>
   <%= form_with model: @comment, local: true, url: user_post_comments_path(user_id: @user.id,post_id: @post.id), class: 'd_flex' do |f| %> 
     <%= f.text_field :text, class: 'form_fild heading_4 h_padding_10' , placeholder: 'Comment...' , rows: 6, required: true  %>
     <%= f.submit "Comment" , class: 'btn green_btn heading_4' %> 
   <% end %> 
</div>

app/views/partials/_like.html.erb
<div>
   <%= form_with model: @like, local: true, url: user_post_likes_path(user_id: @user.id,post_id: @post.id), class: 'd_flex' do |f| %> 
     <%= f.submit "Like" , class: 'btn heading_4' %> 
   <% end %> 
</div>

app/views/partials/_navigation.html.erb
<div class = 'd_flex justify_space_between padding_1r border_bottom'>
  <div class = 'd_flex align_item_center'>
      <% if user_signed_in? %>
        <%= form_with  url: destroy_user_session_path, method: :delete, class: 'd_flex' do |f| %>
          <%= f.submit "Logout" , class: 'btn heading_4' %>
        <% end %>
        <%= link_to 'Home', root_path, class: 'heading_4 secondary_color'%>
        <% else %>
        <%= link_to 'Register', new_user_registration_path, class: 'btn heading_4' %>
        <%= link_to 'Login', new_user_session_path, class: 'btn heading_4' %>
      <% end %>
  </div>
  <div class = 'd_flex'>
    <% if user_signed_in? %>
     <%= link_to current_user.name,  edit_user_registration_path, class: 'align_item_center heading_4 secondary_color' %>
     <% end %>
  </div>
</div>

app/views/partials/_user.html.erb
<div class = 'container'>
<section class = 'd_flex_verical'>
    <div class = 'd_flex user_holder'>
    <% if @user.photo == '' %>
      <img class = 'profile_pic' src = 'https://www.seekpng.com/png/full/428-4287240_no-avatar-user-circle-icon-png.png', alt = 'profile picture'>
      <% else %>
      <img class = 'profile_pic' src = "<%= @user.photo%>", alt = 'profile picture'>
    <% end %>
      <div>
        <h1 class = 'heading_2 secondary_color'><%= @user.name %></h1>
        <p class = 'heading_4 accent_color'>Number of posts : <%= @user.post_counter %></p>
      </div>
    </div>
</section>
</div>

app/views/posts/index.html.erb
<div class = 'container padding_1r'>
<%= render 'partials/navigation' %>
  <h1 class = 'heading_1 primary_color text_center'>User posts</h1>
  <%= render 'partials/user' %>
  <br>
  <% @posts.each do |post| %>
     <%= link_to "#{post.title}" , user_post_path(id: post.id) , {:class => "underline secondary_color heading_3 align_item_center"} %> 
     <p class = 'heading_4'><%= post.text %></p>
     <div class = 'd_flex accent_color'>
       <p>Likes : <%= post.like_counter %></p>
       <p>Comments : <%= post.comment_counter%></p>
     </div>
     <% if post.comment_counter != 0 %>
        <% post.five_recent_comments.each do |comment| %>
          <div class = 'd_flex gap_1 align_center' >
            <% if comment.author.photo == '' %>
              <img class = 'profile_pic comment_pro_pic' src = 'https://www.seekpng.com/png/full/428-4287240_no-avatar-user-circle-icon-png.png', alt = 'profile picture'>
            <% else %>
              <img class = 'profile_pic comment_pro_pic' src = "<%= comment.author.photo%>", alt = 'profile picture'>
            <% end %>
            <h3><%= comment.author.name%></h3>
            <p><%= comment.text%></p>
          </div>
        <% end %>
     <% end %>
     <br>
   <% end %>
  <div class="pagination heading_4 text_center">
    <a href="#">Prev</a>
    <a href="#">1</a>
    <a href="#">Next</a>
  </div>
</div>

app/views/posts/new.html.erb
<div class = 'container padding_1r'>
<%= render 'partials/navigation' %>
<h1 class = 'heading_1 primary_color text_center'>New Post</h1>
<%= render 'partials/user' %><br><br>

<%= form_with model: @post , url: user_posts_path , class: 'text_center' do |f| %>
  <%= f.text_field :title , class: 'form_fild heading_4 h_padding_10', placeholder: 'Title'  %><br><br>
  <%= f.text_area :text, class: 'form_fild heading_4 h_padding_10' , placeholder: 'Post text ...' , rows: 6, required: true %><br><br>
  <%= f.submit "Post" , {:class => 'btn green_btn heading_4'} %>
<% end %>
</div>

app/views/posts/show.html.erb
<div class = 'container padding_1r'>
<%= render 'partials/navigation' %>
  <h1 class = 'heading_1 primary_color text_center'>User Post detail</h1>
  <%= render 'partials/user'%>
  <h2 class = 'heading_3 secondary_color'><%= @post.title %></h2>
  <p class = 'heading_4'><%= @post.text %></p>
  <div class = 'd_flex align_center accent_color'>
    <p>Likes : <%= @post.like_counter %></p>
    <p>Comments : <%= @post.comment_counter%></p>
    <% if can? :destroy, @post %>
      <%= button_to 'Delete Post', user_post_path(user_id: @user.id, id: @post.id), method: :delete , class: 'delete_btn red_color' %>
    <% end %>
  </div>
  <div class = 'd_flex align_center '>
  <%= render 'partials/comment'%><br>
  <%= render 'partials/like'%><br>
  </div>
  <hr class = 'hr-text heading_4' data-content = 'All Comments' style = " width: 100% " ><br>
  <% @post.comments.each do |comment| %>
    <div class = 'd_flex gap_1 align_center' >
    <% if comment.author.photo == '' %>
      <img class = 'profile_pic comment_pro_pic' src = 'https://www.seekpng.com/png/full/428-4287240_no-avatar-user-circle-icon-png.png', alt = 'profile picture'>
    <% else %>
      <img class = 'profile_pic comment_pro_pic' src = "<%= comment.author.photo%>", alt = 'profile picture'>
    <% end %>
      <h3 class = ''><%= comment.author.name%></h3>
      <p><%= comment.text%></p>
    </div>
    <div class = 'padding_l_3rem'>
      <% if can? :manage, comment%>
        <%= button_to 'Delete', user_post_comment_path(user_id: @user.id, post_id: @post.id, id: comment.id), method: :delete , class: 'delete_btn red_color' %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class = 'container padding_1r'>
<%= render 'partials/navigation' %>
<section class = 'd_flex_verical'>
  <h1 class = 'heading_1 primary_color text_center'>All users listed here</h1>
  <% @users.each do |user| %>
  <a href = "/users/<%= user.id %>">
    <div class = 'd_flex user_holder'>
    <% if user.photo == '' %>
      <img class = 'profile_pic' src = 'https://www.seekpng.com/png/full/428-4287240_no-avatar-user-circle-icon-png.png', alt = 'profile picture'>
      <% else %>
      <img class = 'profile_pic' src = "<%= user.photo%>", alt = 'profile picture'>
    <% end %>
      <div>
        <h1 class = 'heading_2 secondary_color'><%= user.name %></h1>
        <p class = 'heading_4 accent_color'>Number of posts : <%= user.post_counter %></p>
      </div>
    </div>
  </a>
  <% end %>
</section>
</div>

app/views/users/show.html.erb
<div class = 'container padding_1r'>
<%= render 'partials/navigation' %>
  <h1 class = 'heading_1 primary_color text_center'>User details</h1>
  <%= render 'partials/user' %>
  <div>
    <h2 class = 'secondary_color'>Bio :</h2>
    <p class = 'heading_4'><%= @user.bio %></p>
  </div>
  <hr class = 'hr-text heading_4' data-content = 'Recent posts' style = " width: 100% " >
  <div class = 'd_flex justify_rigth'> 
    <% if current_user.id == @user.id %>
      <%= link_to 'New Post', new_user_post_path(user_id: @user.id), { :class => 'heading_4 btn green_btn' } %>
    <% end %>
  </div>
  <% if @user.three_recent_posts.length == 0 %>
    <p class = 'heading_4'>No Post !</p>
  <% else %>
  <div class = 'd_flex_verical gap_0 padding_1r'>
   <% @user.three_recent_posts.each do |post| %>
     <h3 class = 'heading_3 secondary_color'><%= post.title %></h3>
     <p class = 'heading_4'><%= post.text %></p>
     <div class = 'd_flex accent_color'>
       <p>Likes : <%= post.like_counter %></p>
       <p>Comments : <%= post.comment_counter%></p>
     </div>
   <% end %>
   <%= link_to "All Posts", user_posts_path(user_id: @user.id) , {:class => "btn heading_4 align_item_center"} %>
 </div>
 <br>
 <% end %>
</div>